### ISSUE TITLE
Feature request, support per-group hooks.

### ISSUE THREAD

**Issue by Dmytro-Komaryst** [sheerun/ava-spec#11]
Support per-group hooks. 
It most important functionality for "described-it" style of the tests.
Are you still planning to develop this functionality in ava-spec?

**Comment by sheerun** [comment]
As written in the readme: "Currently AVA Spec doesn't support per-group hooks. It's a feature planned for 1.1.0."

This feature is blocked because AVA doesn't support different before/after hooks for different tests within same file. Maybe there's a way to hack this but I don't intend to do so.

Maybe you'd like to try to implement it?

**Comment by winfieldaj** [comment]
Is this implemented?
readme: "It's a feature planned for 1.1.0."
package.json: 1.1.1

**Comment by sheerun** [comment]
I've removed this from readme
